parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.034720982265379036
  qx: 0.6228681416670984
  qy: -0.02023463252068046
  qz: -0.7812939850872114
  x: 0.4910479306031795
  y: -0.019733073503095666
  z: 1.0209392866817915
