parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.6315936161897983
  qx: -0.39683222810740704
  qy: 0.3173291141906154
  qz: 0.5855902321680272
  x: 0.2058065935618612
  y: -0.4579844610447736
  z: 0.6569999431191371