parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: -0.22693345
  qx: 0.97041745 
  qy: -0.01664198
  qz: 0.08071071
  x: 0.38030153129558436
  y: -0.3268658732924056
  z: 0.5235625125216197