parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.628513299992371
  qx: -0.3966902975412286
  qy: 0.31945644406350704
  qz: 0.5878396209134354
  x: 0.20653556633756376
  y: -0.4578187563978967
  z: 0.6574470737745264