parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.032642212020451
  qx: -0.4996526752952855
  qy: -0.010936002733848205
  qz: 0.8655415032850137
  x: 1.0635468204220753
  y: -0.02315744712622353
  z: 0.7188767324103629