parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: aruco_marker_frame
transformation:
  qw: 0.08106963186197683
  qx: 0.02624868285152011
  qy: -0.008033703023379135
  qz: -0.99633035738858
  x: 1.1680768943198176
  y: 0.004049134085766015
  z: 0.28032813310595067