parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.5660055735145172
  qx: -0.4453888057678841
  qy: 0.3818427081788497
  qz: 0.5791913748130243
  x: 0.17225115272454666
  y: -0.2968136595176401
  z: 0.8649156972632567