parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: tool_frame
  tracking_base_frame: camera_link
  tracking_marker_frame: aruco_marker_frame
transformation:
  qw: 0.45325293325278926
  qx: -0.4905523301944451
  qy: -0.507049360131059
  qz: 0.5448129369143379
  x: 1.1485363404237483
  y: 0.009071432498892168
  z: 0.26145678377949916