parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: arm
  move_group_namespace: /kinova_gen3_lite
  namespace: /kinova_gen3_lite_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: end_effector_link
  tracking_base_frame: camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.04028590405486268
  qx: 0.38843586644077854
  qy: 0.017529283917433247
  qz: -0.9204278069475227
  x: 1.1331379840966813
  y: -0.037672821171242044
  z: 0.4793054730971652